# Generated by Django 5.1 on 2024-09-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=200, verbose_name='Status do Pedido')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('link_pagamento', models.URLField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido', verbose_name='Pedido')),
            ],
        ),
    ]
