# Generated by Django 5.1 on 2024-10-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='link_pagamento',
            field=models.URLField(blank=True, null=True),
        ),
    ]
