# Generated by Django 5.1 on 2024-09-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_atualizacao_produto_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
