# Generated by Django 5.1 on 2024-10-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Média de Avaliações'),
        ),
    ]
