# Generated by Django 5.1 on 2024-10-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Média de Avaliação'),
        ),
    ]
