# Generated by Django 5.1 on 2024-10-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fotos',
            field=models.ImageField(default=1, upload_to='media/', verbose_name='Fotos'),
            preserve_default=False,
        ),
    ]
