# Generated by Django 5.1 on 2024-10-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fotos',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
