# Generated by Django 5.1 on 2024-09-07 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Valor Total'),
        ),
    ]
