# Generated by Django 5.1 on 2024-09-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_remove_carrinho_produto_alter_carrinho_valor_total_and_more'),
        ('produtos', '0004_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.ManyToManyField(blank=True, to='produtos.produto'),
        ),
        migrations.DeleteModel(
            name='ItemCarrinho',
        ),
    ]
