# Generated by Django 5.1 on 2024-09-22 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0005_carrinho_produto_delete_itemcarrinho'),
        ('produtos', '0004_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'ordering': ('-data_criacao',)},
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='valor_total',
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='carrinho.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
