# Generated by Django 5.1 on 2024-09-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_genero_perfil_numero_perfil_ponto_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outros', 'Outros')], max_length=200, null=True, verbose_name='Gênero'),
        ),
    ]
