# Generated by Django 5.1 on 2024-09-05 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
