# Generated by Django 5.1 on 2024-10-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0003_alter_favorito_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
    ]
